test_project/switches/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='switches'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'<int:Switch_id>/', views.detail, name='detail'),
    path(r'add',views.add_switch, name='add_switch'),
    path(r'<int:Switch_id>/delete',views.delete_switch, name='delete_switch'), 
    path(r'<int:Switch_id>/edit',views.edit_switch, name='edit_switch'),
    path(r'deleted<int:Switch_id>', views.del_switch_confirmed, name='del_switch_confirmed'),
    path(r'<int:Switch_id>/ref', views.data_refresh, name="data_refresh"),
    path(r'<int:Switch_id>/change_port_state', views.change_port_state, name="change_port_state"),
    path(r'<int:Switch_id>/add_vlan', views.add_vlan, name="add_vlan"),
    path(r'<int:Switch_id>/edit_vlan/<int:VID>', views.edit_vlan, name="edit_vlan"),
    path(r'<int:Switch_id>/del_vlan/<int:VID>', views.delete_vlan, name="delete_vlan"),
    path(r'<int:Switch_id>/port_no_vlan',views.port_vlan_remove, name="port_vlan_remove"),
    path(r'<int:Switch_id>/<int:VID>/add_port',views.add_port_vlan, name="add_port_vlan"),
    path(r'<int:Switch_id>/cpu_monitor',views.monitoring_cpu, name="monitoring_cpu"),
    path(r'<int:Switch_id>/cpu_monitor/get_data',views.get_json, name="get_json")
]

test_project/test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from switches import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls'))
]

test_project/users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='users'
from switches import views as views_switches
from users import views as views_user

urlpatterns = [
	path('switches/', include('switches.urls')),
	path('', views_user.my_login, name="login" ),
	path('register/', views_user.register, name="register")
]

test_project/switches/models.py
from django.db import models

# Create your models here.


class Switch_type(models.Model):
	device_type=models.CharField(max_length=35,default='extreme_exos',unique=True)
	def __str__(self):
		return str(self.device_type)


class Device(models.Model):
	switch_type=models.ForeignKey(Switch_type, on_delete=models.CASCADE)
	company_name=models.CharField(max_length=35, default='Extreme networks')
	device_name=models.CharField(max_length=35,default='X450-G2')
	def type(self):
		return str(self.switch_type)
	def __str__(self):
		return ' '.join([str(self.company_name),str(self.device_name)])

class Switch(models.Model):
	IP=models.GenericIPAddressField(protocol='IPv4', unique=True)
	device=models.ForeignKey(Device, on_delete=models.CASCADE,null=True)
	username=models.CharField(max_length=25)
	password=models.CharField(max_length=25)
	ports_number=models.PositiveSmallIntegerField(default=0)
	def __str__(self):
		return str(self.IP)
	def device_name(self):
		return str(Device.objects.get(id=self.device.id))
	def device_type(self):
		return self.device.type()

class Vlan(models.Model):
	switch=models.ForeignKey(Switch, on_delete=models.CASCADE)
	vlan_name=models.CharField(max_length=35)
	VID=models.PositiveSmallIntegerField(null=True)
	def __str__(self):
		return str(self.vlan_name)

class Port(models.Model):
	switch=models.ForeignKey(Switch, on_delete=models.CASCADE)
	vlan=models.CharField(max_length=35, default='No Vlan')
	number=models.PositiveSmallIntegerField()
	port_state=models.BooleanField()
	link_state=models.BooleanField()
	speed=models.PositiveSmallIntegerField(default=100)
	duplex=models.CharField(max_length=10)
	tag=models.BooleanField(default=0)
	def __str__(self):
		return str(self.switch)+', port '+str(self.number)
	def set(self):
		return self.number%2

test_project/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models
from switches.models import Switch

class CustomUser(AbstractUser):
	switches=models.ManyToManyField(Switch)
	

test_project/switches/forms.py
from django import forms



from .models import Switch, Port, Device, Vlan

class auxForm(forms.Form):
	numbers=forms.CharField(max_length=250)


class SwitchForm(forms.ModelForm):
	class Meta:
		model = Switch
		fields = {
			'IP','username','password'
		}

class SwitchForm_without_IP(forms.ModelForm):
	class Meta:
		model = Switch
		fields = {
			'username','password',
		}

class VlanForm(forms.ModelForm):
	class Meta:
		model=Vlan
		fields={
			'vlan_name','VID'
		}

class Dev(forms.Form):
	g=[(f.id,str(f)) for f in Device.objects.all()]
	device=forms.ChoiceField(label='Select Device',choices=[(f.id,str(f)) for f in Device.objects.all()])

test_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username','switches','email','password')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = {'username', 'email','switches','password'}

class UserForm(forms.ModelForm):
	class Meta:
		model=CustomUser
		fields={
		'username','password'
		}

		
class UserFormSwitch(forms.ModelForm):
	class Meta:
		model=CustomUser
		fields={
			'switches'
		}
class confirm_pass(forms.Form):
	confirm_pass=forms.CharField(label='Confirm password',max_length=25)

test_project/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth import authenticate,login, logout
from users.forms import CustomUserCreationForm, CustomUserChangeForm, UserForm
from users.models import CustomUser
from switches.models import Switch
from switches.views import index
import time
# Create your views here.


def my_login(request):
	form=UserForm(request.POST or None)
	context={
		'form':form,
		'error':''
	}
	logout(request)
	if form['username'].value() in [u.username for u in CustomUser.objects.all()]:
		my_user=CustomUser.objects.get(username=form['username'].value())
		if my_user.check_password(form['password'].value()):
			user=authenticate(username=my_user.username,password=form['password'].value())
			if user:
				login(request,user)
				return HttpResponseRedirect('/switches')
		else:
			context['error']='wrong_password'
	else:
		if form['username'].value():
			context['error']='wrong_username'
	return render(request,'switches/user_login.html',context)


def register(request):
	form=CustomUserCreationForm(request.POST or None)
	context={
		'form':form,
		'error':'',
	}
	if form['username'].value() in [u.username for u in CustomUser.objects.all()]:
		context['error']='username_used'
		return render(request, 'switches/user_add.html', context)
	if form['username'].value() and form['password1'].value() and form['password2'].value():
		print('true')
		print(form['password1'].value())
		print(form['password2'].value())
		if form['password1'].value()==form['password2'].value():
			my_user=CustomUser(username=form['username'].value())
			my_user.set_password(form['password1'].value())
			my_user.save()
			return HttpResponseRedirect('/')
		else:
			context['error']='conf_password_error'
		print(context['error'])

	return render(request, 'switches/user_add.html', context)

def my_logout(request):
	print('logging out',request.user)
	logout(request)
	return HttpResponseRedirect('/')

test_project/templates/switches/add_vlan.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Vlan {{switch.IP}}</title>
</head>
<style>
body{
	background-color: #d5d5d5;
	height: 100%;
}
div{
	padding: 8px;
}
#button_quit{
	box-sizing: border-box;
	display: inline-block;
	font-style: initial;
	text-decoration:none;
	padding: 5px;
	border:2px black solid;
	width: 60px;
	text-align:center;
	margin-top: 10px;
	color:black;
	background-color: coral;
}
#button_quit:hover{	color: red;}
</style>
<body>
	<form method="POST">
		<fieldset>
			{% csrf_token %}
			<legend>Vlan info:</legend>
			{% if error %}{% include "error_case.html" %}{% endif %}
			<div><label for="id_vlan_name">Vlan name:</label> <input type="text" name="vlan_name" maxlength="35" required="" id="id_vlan_name"></div>
			<div><label for="id_VID">VID:</label> <input type="number" name="VID" min="0" value="{{first_unused}}" required="" id="id_VID"></div>
			{{conf_form.as_p}}
			<input type="submit" name="Save">
		</fieldset>
	</form>
	<a id="button_quit" href="/switches/{{switch.id}}">Quit</a>

</body>
</html>

test_project/templates/switches/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Ports for {{switch.IP}}</title>
<!--{%load static%}
<link rel="stylesheet" type="text/css" href="{% static '/css/detail.css'%}">-->
<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="//d3js.org/topojson.v1.min.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<style>{% include 'switches/static/css/detail.css'%}
</style>
</head>
<body>
	<div id="navbar">
		<a href="/switches">Home</a>
		<a href="/" style="float:right">Logout</a>
		<a href="delete" style="float:right;">Delete switch</a>
		{% if user.is_superuser %}
		<a href="/admin" style="float:right">Admin</a>
		{%endif%}
		<div id="dropswitches">
			<button id="dropbtn">Switches</button>
    		<div id="dropdown-content">
      			{% for i in user.switches.all %}
      				<a href="/switches/{{i.id}}">{{i.IP}}</a>
      			{% endfor %}
      		</div>
  		</div>
	</div> 
	<div id="inside">
		
		<div id="main_info" >
			<div style="display: inline-block;">
				<b>Switch info</b>:<br>
				IP: {{switch.IP}},<br> 
				username: {{switch.username}},<br>
				password: {% if switch.password == "" %}no password{%else%}{{switch.password}}{%endif%}<br>
				device: {{switch.device_name}}<br>
				number of ports: {{switch.ports_number}}
				{% if error %}
					{% include "error_case.html" %}
				{% endif %}
				{% if form %}<p style="display: none;"><label for="id_numbers">Numbers:</label> <input type="text" name="numbers" maxlength="250" required="" id="id_numbers"></p>{%endif%}
			</div>
			<div id='cpu_res' style="display: none;float: right;"></div>
		</div>

		<a href="/switches/{{switch.id}}/edit"><div id="edit_botton">Edit</div></a>
		{%if ports%}
		<a href="/switches/{{switch.id}}/ref"><div id="refresh_botton">Refresh</div></a>
		<div class="vlans_button"  style=" width: 130px;" onclick="show_cpu()" ondblclick='window.location.href="/switches/{{switch.id}}/cpu_monitor"'>CPU monitor</div>
		<br>
		<div id="the_switch">
			<div id="switch_name">{{switch.device_name}}</div>
			{% for port in ports%}
			{% if port.set == 1 %}
			<a onclick="js_change({{port.number}})"><div style="background-color: {% if port.port_state and port.link_state %}#00e600{%else%}{%if port.port_state%}#FFBF00{%else%}#FA5858{%endif%}{%endif%};" title="Port Number:{{port.number}}
vlan:{{port.vlan}}
state:{% if port.port_state and port.link_state %}Up{%else%}{%if port.port_state%}Down{%else%}Admin Down{%endif%}{%endif%}
tag:{%if port.tag %}Tagged{%else%}Untagged{%endif%}{% if port.speed != 0%}
speed:{{port.speed}}
duplex:{{port.duplex}}{%endif%}" class="port" id="port{{port.number}}" >{{port.number}}</div></a>
			{%endif%}
			{%endfor%}
			<br style="width: 950px;">
			{% for port in ports%}
			{% if port.set == 0 %}
			
			<a onclick="js_change({{port.number}})"><div style="background-color: {% if port.port_state and port.link_state %}#00e600{%else%}{%if port.port_state%}#FFBF00{%else%}#FA5858{%endif%}{%endif%};" title="Port Number:{{port.number}}
vlan:{{port.vlan}}
state:{% if port.port_state and port.link_state %}Up{%else%}{%if port.port_state%}Down{%else%}Admin Down{%endif%}{%endif%}
tag:{%if port.tag %}Tagged{%else%}Untagged{%endif%}{% if port.speed != 0%}
speed:{{port.speed}}
duplex:{{port.duplex}}{%endif%}" class="port" id="port{{port.number}}" >{{port.number}}</div></a>
			{%endif%}
			{%endfor%}
		</div>
		{% else %}
		<div>No ports available</div>
		{%endif%} 
		<br>
		<form id="want_sub" method="post" action="">
			{% csrf_token %}
		<p style="display: none"><label for="id_numbers">Numbers:</label> <input type="text" name="numbers" maxlength="250" required="" id="id_numbers" value=""></p>
		<div id="change_botton" onclick="form_port()";><a id="change" ></a></div>
		<div id="change_botton_vlan" onclick="form_vlan()"><a id="port_no_vlan" ></a></div>
		</form>
		<br>

		{%if vlans%}
		<div class="vlans_button" id="vlans_button1" onclick="vlan_show()">Vlans</div>
		<div class="vlans_button" style="width: 100px;" onclick="print_ports({{ports_state}},{{switch.ports_number}})">Port state</div>
		<div class="vlans_button" style="width: 80px;" onclick="duplex_show({{ports_duplex}},{{switch.ports_number}})">Duplex</div>
		
		<br>
		<div id="vlans_detail">
			<div class="vlans_button" id="vlans_button2" onclick="vlan_hide()" style="width: 120px;" onmouseover="">Hide vlans</div>		
			<a href="/switches/{{switch.id}}/add_vlan"><div class="vlans_button"  style="width: 95px;">Add Vlan</div></a>
			<ul id="vlan_list">
				{% for vlan in vlans%}
				<li class="vlan_obj">
					<span class='tag'>{{vlan.vlan_name}} [{{vlan.VID}}]:</span>
					<ul class='in_tag'>
						<li onclick="show_vlan('{{vlan.vlan_name}}',{{ports_vlan}},{{switch.ports_number}})"><span class='tag' style="margin-bottom: 1px;">Ports</span>
							<ul class='in_tag'>
								<li>{%if vlan.vlan_name in used_vlans%}{% for port in ports %}{% if port.vlan == vlan.vlan_name %}{{port.number}} {%endif%}{%endfor%}{%else%}no ports assigned{%endif%}
								</li>
							</ul>
						</li>
						<div style="margin-top: 7px;"></div>
						<a class='button' href="/switches/{{switch.id}}/edit_vlan/{{vlan.VID}}"><li id='edit_vlan_button'> Edit</li></a>
						<a class='button' href="/switches/{{switch.id}}/del_vlan/{{vlan.VID}}"><li id="remove_vlan_button">Remove</li></a>
						<a class='button' href="/switches/{{switch.id}}/{{vlan.VID}}/add_port"><li id="add_port_vlan_button">Add Ports</li></a>
					</ul>
				</li>
				{%endfor%}
				
			</ul>

		</div>
		{%endif%}
		<br>
		<a href="/switches" style="padding: 5px;" class="back">Go back</a>
		<div id="notes_continer"><p id="notes_title">Notes:</p>
			<div id="notes"></div>
		</div>
	</div>

<script type="text/javascript" src="cpu_monitor/get_data"></script>
<script>{% include 'switches/static/js/detail.js'%}
	var cpu_data=[['Time','Cpu'],['no_value',0]]
	function drawChart() {
		var data = google.visualization.arrayToDataTable(cpu_data);	
		var options = {
			title: 'CPU usage',
			curveType: 'function',
			legend: { position: 'bottom' }
			};
		var chart = new google.visualization.LineChart(document.getElementById('cpu_res'))
		chart.clearChart()
		chart.draw(data, options);
	}
	
	show_cpu('pass')
	
	function show_cpu(r='not_pass'){
		d=document.getElementById('cpu_res');
		if (d.style.display==='none' & r!='pass'){
			d.style.display='inline-block';
		}
		else if (r!='pass'){
			d.style.display='none'
		}
		d3.json("cpu_monitor/get_data", function(error, data){
		    if(error) return console.error(error);
		    if (cpu_data.length>1)
		    {
		    	cpu_data=[['Time','Cpu']]
		    }
		    if (data.length!=0)
		    {
		    	for (let k=0;k<data.length;k++)
		    	{
		    		cpu_data.push([data[k].time,Number(data[k].cpu)])
		   		}
			}
			else{
				cpu_data=[['Time','Cpu'],['no_value',-1]]
			}
		})
		google.charts.load('current', {'packages':['corechart']});		
		google.charts.setOnLoadCallback(drawChart);
		if (d.style.display!='none')
		{
			setTimeout("show_cpu('pass')", 3500);
		}
	}
		
</script>


</body>
</html>

test_project/templates/switches/edit_vlan.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Vlan {{switch.IP}}</title>
</head>
<style>
body{
	background-color: #d5d5d5;
	height: 100%;
}
div{
	padding: 8px;
}
#button_quit{
	box-sizing: border-box;
	display: inline-block;
	font-style: initial;
	text-decoration:none;
	padding: 5px;
	border:2px black solid;
	width: 60px;
	text-align:center;
	margin-top: 10px;
	color:black;
	background-color: coral;
}
#button_quit:hover{	color: red;}
</style>
<body>
	<form method="POST">
		<fieldset>
			{% csrf_token %}
			<legend>Vlan info:</legend>
			{% if error %}{% include "error_case.html" %}{% endif %}
			<div><label for="id_vlan_name">Vlan name:</label> <input type="text" name="vlan_name" maxlength="35" required="", value="{{vlan.vlan_name}}" id="id_vlan_name"></div>
			<div><label for="id_VID">VID:</label> <input type="number" name="VID" min="0" value="{{vlan.VID}}" required="" id="id_VID"></div>
			<input type="submit" name="Save">
		</fieldset>
	</form>
	<a id="button_quit" href="/switches/{{switch.id}}">Quit</a>

</body>
</html>

test_project/templates/switches/error_case.html
{% if error == "user" %}
	<h6> Wrong username or password </h6>
{%endif%}
{% if error == "unknown" %}
	<h6> Something went wrong </h6>
{%endif%}
{% if error == "not_reachable" %}
	<h6> Host not reachable </h6>
{% endif %}
{% if error == "not_supported" %}
	<h6> Device type not supported </h6>
{%endif%}
{% if error == "permission_denied" %}
	<h6> You don't have the permision to edit this switch </h6>
{%endif%}
{% if error == "permission_denied_admin" %}
	<h6> Can't do this change to the system </h6>
{%endif%}
{%if error == 'used_vlan_name'%}
	<h6> Already exist a vlan with this name </h6>
{%endif%}
{%if error == 'used_VID'%}
	<h6> Already exist a vlan with this Vlan ID</h6>
{%endif%}
{%if error == 'name_error'%}
	<h6> This name can't be used </h6>
{%endif%}
{%if error == 'need_refresh'%}
	<h6> Please refresh the data </h6>
{%endif%}
{%if error == 'conf_password_error'%}
	<h6> The passworld doesn't match </h6>
{%endif%}
{%if error == 'username_used'%}
	<h6>Username already used</h6>
{%endif%}
{%if error == 'wrong_username'%}
	<h6 style="text-align: left;margin-left: 70px;">Wrong username</h6>
{%endif%}
{%if error == 'wrong_password'%}
	<h6 style="text-align: left;margin-left: 70px;">Wrong password</h6>
{%endif%}
{% if error == 'select_error' %}
	<h6>Please select ports</h6>
{%endif%}

test_project/templates/switches/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Switches</title>
<style>
 {% include 'switches/static/css/index.css' %}


</style>

</head>

<body>
	<div id="navbar">
		<a href="/switches">Home</a>
		<a href="/" style="float:right">Logout</a>
		{% if user.is_superuser %}
		<a href="/admin" style="float:right">Admin</a>
		{%endif%}
		<div id="dropswitches">
			<button id="dropbtn">Switches</button>
    		<div id="dropdown-content">
      			{% for i in user.switches.all %}
      				<a href="/switches/{{i.id}}">{{i.IP}}</a>
      			{% endfor %}
      		</div>
  		</div>
	</div> 
	<div id="inside">
		<h3>
			Switches list
		</h3>
		<br>
		<ui>
			{% for s in switches %}
				<li><a href="/switches/{{s.id}}">{{s.IP}}</a></li>
			{% endfor %}
		</ui>
		<br>
		<a href="/switches/add" class="add">Add switch here</a>
	</div>
</body>
<script>
	
	function switches(arr){
		for (var i = 0; i < arr.length; i++) {
			console.log(arr[i])
		}
	}
</script>
</html>

test_project/templates/switches/port_add.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Port for Switch {{switch.IP}}}</title>
<style>
body{
	background-color: #e7e7e7;
}
a{
	box-sizing: border-box;
	display: inline-block;
	font-style: initial;
	text-decoration:none;
	padding: 5px;
	border:3px black solid;
	margin-top: 10px;
	color:white;
	background-color: coral;
}
a:hover{
	color: red;
	background-color: #454545;
	font-style: italic;
}


</style>
</head>
<body>
	<form method="POST">
		<fieldset>
			{% csrf_token %}
			<legend>Port info:</legend>
			<div>Switch {{switch.id}}: IP: {{switch.IP}}</div>
			{{form.as_p}}
			<input type="submit" name="Save">
		</fieldset>
	</form>
	<a href="/switches/{{switch.id}}">Quit</a>
</body>
</html>

test_project/templates/switches/supported_list.html
<h3>Supported list:</h3>
<ui><li>    "a10": A10SSH,</li>
<li>    "accedian": AccedianSSH,</li>
<li>    "alcatel_aos": AlcatelAosSSH,</li>
<li>    "alcatel_sros": AlcatelSrosSSH,</li>
<li>    "apresia_aeos": ApresiaAeosSSH,</li>
<li>    "arista_eos": AristaSSH,</li>
<li>    "aruba_os": ArubaSSH,</li>
<li>    "avaya_ers": ExtremeErsSSH,</li>
<li>    "avaya_vsp": ExtremeVspSSH,</li>
<li>    "brocade_fastiron": RuckusFastironSSH,</li>
<li>    "brocade_netiron": ExtremeNetironSSH,</li>
<li>    "brocade_nos": ExtremeNosSSH,</li>
<li>    "brocade_vdx": ExtremeNosSSH,</li>
<li>    "brocade_vyos": VyOSSSH,</li>
<li>    "checkpoint_gaia": CheckPointGaiaSSH,</li>
<li>    "calix_b6": CalixB6SSH,</li>
<li>    "ciena_saos": CienaSaosSSH,</li>
<li>    "cisco_asa": CiscoAsaSSH,</li>
<li>    "cisco_ios": CiscoIosSSH,</li>
<li>    "cisco_nxos": CiscoNxosSSH,</li>
<li>    "cisco_s300": CiscoS300SSH,</li>
<li>    "cisco_tp": CiscoTpTcCeSSH,</li>
<li>    "cisco_wlc": CiscoWlcSSH,</li>
<li>    "cisco_xe": CiscoIosSSH,</li>
<li>    "cisco_xr": CiscoXrSSH,</li>
<li>    "cloudgenix_ion": CloudGenixIonSSH,</li>
<li>    "coriant": CoriantSSH,</li>
<li>    "dell_dnos9": DellForce10SSH,</li>
<li>    "dell_force10": DellForce10SSH,</li>
<li>    "dell_os6": DellDNOS6SSH,</li>
<li>    "dell_os9": DellForce10SSH,</li>
<li>    "dell_os10": DellOS10SSH,</li>
<li>    "dell_powerconnect": DellPowerConnectSSH,</li>
<li>    "dell_isilon": DellIsilonSSH,</li>
<li>    "endace": EndaceSSH,</li>
<li>    "eltex": EltexSSH,</li>
<li>    "enterasys": EnterasysSSH,</li>
<li>    "extreme": ExtremeExosSSH,</li>
<li>    "extreme_ers": ExtremeErsSSH,</li>
<li>    "extreme_exos": ExtremeExosSSH,</li></li>
<li>    "extreme_netiron": ExtremeNetironSSH,</li>
<li>    "extreme_nos": ExtremeNosSSH,</li>
<li>    "extreme_slx": ExtremeSlxSSH,</li>
<li>    "extreme_vdx": ExtremeNosSSH,</li>
<li>    "extreme_vsp": ExtremeVspSSH,</li>
<li>    "extreme_wing": ExtremeWingSSH,</li>
<li>    "f5_ltm": F5TmshSSH,</li>
<li>    "f5_tmsh": F5TmshSSH,</li>
<li>    "f5_linux": F5LinuxSSH,</li>
<li>    "flexvnf": FlexvnfSSH,</li>
<li>    "fortinet": FortinetSSH,</li>
<li>    "generic_termserver": TerminalServerSSH,</li>
<li>    "hp_comware": HPComwareSSH,</li>
<li>    "hp_procurve": HPProcurveSSH,</li>
<li>    "huawei": HuaweiSSH,</li>
<li>    "huawei_vrpv8": HuaweiVrpv8SSH,</li>
<li>    "ipinfusion_ocnos": IpInfusionOcNOSSSH,</li>
<li>    "juniper": JuniperSSH,</li>
<li>    "juniper_junos": JuniperSSH,</li>
<li>    "linux": LinuxSSH,</li>
<li>    "mikrotik_routeros": MikrotikRouterOsSSH,</li>
<li>    "mikrotik_switchos": MikrotikSwitchOsSSH,</li>
<li>    "mellanox": MellanoxMlnxosSSH,</li>
<li>    "mellanox_mlnxos": MellanoxMlnxosSSH,</li>
<li>    "mrv_lx": MrvLxSSH,</li>
<li>    "mrv_optiswitch": MrvOptiswitchSSH,</li>
<li>    "netapp_cdot": NetAppcDotSSH,</li>
<li>    "netscaler": NetscalerSSH,</li>
<li>    "oneaccess_oneos": OneaccessOneOSSSH,</li>
<li>    "ovs_linux": OvsLinuxSSH,</li>
<li>    "paloalto_panos": PaloAltoPanosSSH,</li>
<li>    "pluribus": PluribusSSH,</li>
<li>    "quanta_mesh": QuantaMeshSSH,</li>
<li>    "rad_etx": RadETXSSH,</li>
<li>    "ruckus_fastiron": RuckusFastironSSH,</li>
<li>    "ubiquiti_edge": UbiquitiEdgeSSH,</li>
<li>    "ubiquiti_edgeswitch": UbiquitiEdgeSSH,</li>
<li>    "vyatta_vyos": VyOSSSH,</li>
<li>    "vyos": VyOSSSH</li>
</ui>

test_project/templates/switches/switch_add.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Switch</title>
<style>
body{
	background-color: #e7e7e7;
}
.a{
	box-sizing: border-box;
	display: inline-block;
	font-style: initial;
	text-decoration:none;
	padding: 5px;
	border:2px black solid;
	width: 60px;
	text-align:center;
	margin-top: 10px;
	color:black;
	background-color: coral;
}
.a:hover{
	color: red;
}
h6{
	margin:0;
	padding: 0;
	color: red;
	font-size: 15px;
}


</style>
</head>
<body>
	<form method="POST">
		<fieldset>
			{% csrf_token %}
			<legend>Switch info:</legend>
			{% if error %}{% include "error_case.html" %}{% endif %}
			<p><label for="id_IP">IP:</label> <input type="text" name="IP" required="" id="id_IP"></p>
			<p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="25" required="" id="id_username"></p>
			<p><label for="id_password">Password:</label> <input type="text" name="password" maxlength="25" id="id_password"></p>			
			{{form_dev.as_p}}
			<input type="submit" name="Save">
		</fieldset>
	</form>
	<a class="a" href="/switches/">Quit</a>
</body>
</html>